# Project Information
site_name: 'MrHelper'
site_description: 'Medical Review Helper'
site_author: 'dearfad'
site_url: 'https://dearfad.github.io/mrhelper/'

# Repository
repo_name: 'dearfad/mrhelper'
repo_url: 'https://github.com/dearfad/mrhelper'

# Copyright
copyright: 'Copyright &copy; 2018 dearfad'

# Configuration
theme:
  name: 'material'
  language: 'zh'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/dearfad'


# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: underscore
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Javascripts
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML' 

# Contents
nav:
  - 简介: 'index.md'
  - 快速入门: 'quickstart.md'
  - 源码说明:
      - MRHPKG:
          - FILTERS:
              - PUBMED: 'mrhpkg/filters/pubmed.md'
